---
title: "SP500_J_Park"
author: "Jim Park"
date: "November 7, 2017"
output: html_document
---

#Download S&P 500 index
```{r, echo=TRUE}
library(tseries)
## S&P 500 (^GSPC)
###    SNP - SNP Real Time Price. Currency in USD
# TODO: Download the data of SP500 '^gspc'.
SNPdata <- get.hist.quote('^gspc',quote="Close")
```

#log returns
```{r, echo=TRUE}
# TODO: Calculate the log returns, which is the subtraction of log(lag(SNPdata)) and log(SNPdata)
SNPret <- log(lag(SNPdata)) - log(SNPdata)
```

#volitility measure
```{r, echo=TRUE}
# TODO: Calculate volatility measure that is to multiply sd(SNPret),sqrt(250), 100
SNPvol <- sd(SNPret) * sqrt(250) * 100
```
#Volitility Function
```{r, echo=TRUE}
## Define getVol function for volatility
getVol <- function(d, logrets) {
	var = 0
	lam = 0
	varlist <- c()

	for (r in logrets) {
		lam = lam*(1 - 1/d) + 1
	  var = (1 - 1/lam)*var + (1/lam)*r^2
		varlist <- c(varlist, var)
	}

	sqrt(varlist)
}
```

#volitility over length of series 10, 30, and 100
```{r, echo=TRUE}
# Calculate volatility over entire length of series for various three different decay factors: 10 30. 100

# TODO: call getVol function with the parameters: 10,SNPret
volest <- getVol(10,SNPret)

# TODO: call getVol function with the parameters: 30,SNPret
volest2 <- getVol(30,SNPret)

# TODO: call getVol function with the parameters: 100,SNPret
volest3 <- getVol(100,SNPret)
```

#Plot volitility
```{r, echo=TRUE}
# Plot the results, overlaying the volatility curves on the data, just as was done in the S&P example.
plot(volest,type="l")

# TODO: Add connected line segments for volest2 with the parameters: type="l",col="red"
lines(volest2, type="l",col="red")

# TODO: Add connected line segments for volest3 with the parameters: type="l",col="blue"
lines(volest3, type="l",col="blue")
```